// ============================================================================
//  DO NOT EDIT THIS FILE.
//
//  Generated from contracts/schema/*.json by contracts/codegen.sh
//  (quicktype 23.2.6). Any hand edit is erased by the next run and
//  will silently desync the TypeScript side of the contract from the other.
//
//  To change a type: edit the JSON Schema, run ./contracts/codegen.sh,
//  and commit both generated files together.
// ============================================================================

import * as z from "zod";

// Metres. There is no other option; the field exists to make the assumption unmissable.

export const UnitsSchema = z.enum([
    "m",
]);
export type Units = z.infer<typeof UnitsSchema>;

// `measured` means drive IBL from ARKit's light estimate; the others are fixed rigs a style
// op can select.

export const LightingPresetSchema = z.enum([
    "daylight",
    "evening",
    "measured",
    "overcast",
    "warm_lamp",
]);
export type LightingPreset = z.infer<typeof LightingPresetSchema>;

// RoomPlan's 16 object categories, verbatim.

export const SceneObjectClassSchema = z.enum([
    "bathtub",
    "bed",
    "chair",
    "dishwasher",
    "fireplace",
    "frame",
    "oven",
    "refrigerator",
    "shelf",
    "sink",
    "sofa",
    "stairs",
    "storage",
    "stove",
    "table",
    "television",
    "toilet",
    "washerDryer",
]);
export type SceneObjectClass = z.infer<typeof SceneObjectClassSchema>;

// Which point of the bounding box `pose.position` refers to. base_center is the default for
// floor-standing furniture.

export const PivotSchema = z.enum([
    "base_back_center",
    "base_center",
    "center",
]);
export type Pivot = z.infer<typeof PivotSchema>;

// real = measured by RoomPlan. inferred = reconstructed from measured room boundaries.
// virtual = introduced by an op.

export const ProvenanceSchema = z.enum([
    "inferred",
    "real",
    "virtual",
]);
export type Provenance = z.infer<typeof ProvenanceSchema>;

// Lifecycle of an entity. `hidden` entities still EXIST in the graph — undo has to be able
// to bring them back — but are never drawn and never offered as a deixis candidate.

export const EntityStateSchema = z.enum([
    "hidden",
    "present",
    "replaced",
]);
export type EntityState = z.infer<typeof EntityStateSchema>;


export const RelationPredicateSchema = z.enum([
    "adjacent_to",
    "against_wall",
    "blocks",
    "in_front_of",
    "on_top_of",
    "under_window",
]);
export type RelationPredicate = z.infer<typeof RelationPredicateSchema>;


export const SurfaceClassSchema = z.enum([
    "ceiling",
    "door",
    "floor",
    "opening",
    "wall",
    "window",
]);
export type SurfaceClass = z.infer<typeof SurfaceClassSchema>;


export const SwingDirectionSchema = z.enum([
    "inward",
    "outward",
    "sliding",
]);
export type SwingDirection = z.infer<typeof SwingDirectionSchema>;

// Side the hinge is on, viewed from inside the room facing the door.

export const SwingHingeSchema = z.enum([
    "left",
    "right",
]);
export type SwingHinge = z.infer<typeof SwingHingeSchema>;


export const OpSourceSchema = z.enum([
    "style_planner",
    "system",
    "tap",
    "voice",
]);
export type OpSource = z.infer<typeof OpSourceSchema>;


export const NoteSideSchema = z.enum([
    "above",
    "any",
    "back",
    "front",
    "left",
    "right",
]);
export type NoteSide = z.infer<typeof NoteSideSchema>;


export const NoteTypeSchema = z.enum([
    "circulation",
    "clearance",
    "outlet_access",
    "reach",
    "sightline",
]);
export type NoteType = z.infer<typeof NoteTypeSchema>;

// applied = requested pose was legal and used verbatim. adjusted = the solver moved it and
// the model must say so. rejected = nothing changed; `alternatives` carries the offer.

export const ReportStatusSchema = z.enum([
    "adjusted",
    "applied",
    "rejected",
]);
export type ReportStatus = z.infer<typeof ReportStatusSchema>;


export const ViolationTypeSchema = z.enum([
    "blocks_door_swing",
    "blocks_walkway",
    "blocks_window",
    "floating",
    "intersection",
    "out_of_bounds",
    "unsupported",
]);
export type ViolationType = z.infer<typeof ViolationTypeSchema>;

// How the target should sit relative to `anchor_id`. This is the model's entire vocabulary
// for position — it has no others.

export const PlacementRelationSchema = z.enum([
    "absolute",
    "against_wall",
    "away_from",
    "behind",
    "beside",
    "centered_in",
    "facing",
    "in_front_of",
    "on_top_of",
    "under",
]);
export type PlacementRelation = z.infer<typeof PlacementRelationSchema>;


export const PlacementSideSchema = z.enum([
    "back",
    "east",
    "front",
    "left",
    "north",
    "right",
    "south",
    "west",
]);
export type PlacementSide = z.infer<typeof PlacementSideSchema>;


export const OpTypeSchema = z.enum([
    "ADD_OBJECT",
    "APPLY_STYLE",
    "CHANGE_COLOR",
    "CHANGE_MATERIAL",
    "DELETE_OBJECT",
    "MODIFY_FLOOR",
    "MODIFY_WALL",
    "MOVE_OBJECT",
    "REPLACE_OBJECT",
    "RESIZE_OBJECT",
    "ROTATE_OBJECT",
    "UNDO",
]);
export type OpType = z.infer<typeof OpTypeSchema>;


export const HitTypeSchema = z.enum([
    "floor",
    "none",
    "object",
    "surface",
]);
export type HitType = z.infer<typeof HitTypeSchema>;

// Which input produced the ray on this frame. Flips per frame; the UI shows it so a failing
// tracker is visible rather than silent.

export const SourceSchema = z.enum([
    "hand",
    "phone",
]);
export type Source = z.infer<typeof SourceSchema>;

// Which demonstrative this candidate is the best fit for. `this` favours near+centred,
// `that` far+centred, `there` the floor hit, `it` the salience stack.

export const DemonstrativeSchema = z.enum([
    "it",
    "that",
    "there",
    "this",
]);
export type Demonstrative = z.infer<typeof DemonstrativeSchema>;


export const FrameDirectionSchema = z.enum([
    "client_to_server",
    "server_to_client",
]);
export type FrameDirection = z.infer<typeof FrameDirectionSchema>;


export const ErrorCodeSchema = z.enum([
    "model_error",
    "rate_limited",
    "solver_rejected",
    "token_expired",
    "transport",
    "unknown_entity",
]);
export type ErrorCode = z.infer<typeof ErrorCodeSchema>;


export const HintKindSchema = z.enum([
    "clarify",
    "highlight",
    "thinking",
]);
export type HintKind = z.infer<typeof HintKindSchema>;

// client_to_server: audio | context | applied | tap.  server_to_client: hint | ops | speech
// | clarify | error.

export const WsFrameTypeSchema = z.enum([
    "applied",
    "audio",
    "clarify",
    "context",
    "error",
    "hint",
    "ops",
    "speech",
    "tap",
]);
export type WsFrameType = z.infer<typeof WsFrameTypeSchema>;

export const BoundsSchema = z.object({
    "area_m2": z.number(),
    "ceiling_height": z.number(),
    "floor_polygon": z.array(z.array(z.number())),
});
export type Bounds = z.infer<typeof BoundsSchema>;

export const FrameSchema = z.object({
    "units": UnitsSchema,
    "up": z.array(z.number()),
    "world_transform": z.array(z.number()),
});
export type Frame = z.infer<typeof FrameSchema>;

export const LightingSchema = z.object({
    "ambient_cct": z.number(),
    "intensity": z.number(),
    "preset": LightingPresetSchema,
});
export type Lighting = z.infer<typeof LightingSchema>;

export const PoseSchema = z.object({
    "position": z.array(z.number()),
    "yaw": z.number(),
});
export type Pose = z.infer<typeof PoseSchema>;

export const OccupancySchema = z.object({
    "grid_rle": z.array(z.number()),
    "origin": z.array(z.number()),
    "resolution_m": z.number(),
    "size": z.array(z.number()),
});
export type Occupancy = z.infer<typeof OccupancySchema>;

export const RelationSchema = z.object({
    "distance": z.union([z.number(), z.null()]).optional(),
    "object": z.string(),
    "predicate": RelationPredicateSchema,
    "subject": z.string(),
});
export type Relation = z.infer<typeof RelationSchema>;

export const PlaneSchema = z.object({
    "normal": z.array(z.number()),
    "offset": z.number(),
});
export type Plane = z.infer<typeof PlaneSchema>;

export const SwingSchema = z.object({
    "arc_radius": z.number(),
    "direction": SwingDirectionSchema,
    "hinge": SwingHingeSchema,
});
export type Swing = z.infer<typeof SwingSchema>;

export const CausedBySchema = z.object({
    "source": OpSourceSchema,
    "transcript": z.string(),
    "utterance_id": z.string(),
});
export type CausedBy = z.infer<typeof CausedBySchema>;

export const AlternativeSchema = z.object({
    "position": z.array(z.number()),
    "score": z.number(),
    "summary": z.string(),
    "yaw": z.number(),
});
export type Alternative = z.infer<typeof AlternativeSchema>;

export const ReportPoseSchema = z.object({
    "position": z.array(z.number()),
    "yaw": z.number(),
});
export type ReportPose = z.infer<typeof ReportPoseSchema>;

export const RemainingNoteSchema = z.object({
    "recommended_m": z.number(),
    "side": NoteSideSchema,
    "type": NoteTypeSchema,
    "value_m": z.number(),
});
export type RemainingNote = z.infer<typeof RemainingNoteSchema>;

export const ViolationResolvedSchema = z.object({
    "overlap_m": z.number(),
    "type": ViolationTypeSchema,
    "with": z.string(),
});
export type ViolationResolved = z.infer<typeof ViolationResolvedSchema>;

export const AudioFrameSchema = z.object({
    "channels": z.number(),
    "pcm_b64": z.string(),
    "sample_rate": z.number(),
});
export type AudioFrame = z.infer<typeof AudioFrameSchema>;

export const ClarifyFrameSchema = z.object({
    "candidates": z.array(z.string()),
    "question": z.string(),
});
export type ClarifyFrame = z.infer<typeof ClarifyFrameSchema>;

export const CameraStateSchema = z.object({
    "forward": z.array(z.number()),
    "fov_deg": z.number(),
    "position": z.array(z.number()),
});
export type CameraState = z.infer<typeof CameraStateSchema>;

export const CrosshairRaySchema = z.object({
    "hit_distance_m": z.union([z.number(), z.null()]),
    "hit_entity": z.union([z.null(), z.string()]),
    "hit_point": z.union([z.array(z.number()), z.null()]),
    "hit_type": HitTypeSchema,
});
export type CrosshairRay = z.infer<typeof CrosshairRaySchema>;

export const OpenRectSchema = z.object({
    "center": z.array(z.number()),
    "size": z.array(z.number()),
    "yaw": z.number(),
});
export type OpenRect = z.infer<typeof OpenRectSchema>;

export const WallClearanceSchema = z.object({
    "free_depth_m": z.number(),
    "surface_id": z.string(),
});
export type WallClearance = z.infer<typeof WallClearanceSchema>;

export const LastFloorHitSchema = z.object({
    "age_ms": z.number(),
    "point": z.union([z.array(z.number()), z.null()]),
});
export type LastFloorHit = z.infer<typeof LastFloorHitSchema>;

export const LastTapSchema = z.object({
    "age_ms": z.number(),
    "entity": z.union([z.null(), z.string()]),
});
export type LastTap = z.infer<typeof LastTapSchema>;

export const PointingRaySchema = z.object({
    "confidence": z.number(),
    "screen_point": z.array(z.number()),
    "source": SourceSchema,
});
export type PointingRay = z.infer<typeof PointingRaySchema>;

export const RankedCandidateSchema = z.object({
    "demonstrative": DemonstrativeSchema,
    "entity_id": z.string(),
    "score": z.number(),
});
export type RankedCandidate = z.infer<typeof RankedCandidateSchema>;

export const VisibleEntitySchema = z.object({
    "angular_offset_deg": z.number(),
    "class": z.string(),
    "distance_m": z.number(),
    "id": z.string(),
    "occluded": z.boolean(),
    "salience": z.number(),
    "screen_area_frac": z.number(),
});
export type VisibleEntity = z.infer<typeof VisibleEntitySchema>;

export const ErrorFrameSchema = z.object({
    "code": ErrorCodeSchema,
    "message": z.string(),
    "recoverable": z.union([z.boolean(), z.null()]).optional(),
});
export type ErrorFrame = z.infer<typeof ErrorFrameSchema>;

export const HintFrameSchema = z.object({
    "entity_ids": z.union([z.array(z.string()), z.null()]).optional(),
    "kind": HintKindSchema,
    "text": z.union([z.null(), z.string()]).optional(),
});
export type HintFrame = z.infer<typeof HintFrameSchema>;

export const SpeechFrameSchema = z.object({
    "audio_b64": z.union([z.null(), z.string()]).optional(),
    "final": z.union([z.boolean(), z.null()]).optional(),
    "text": z.string(),
});
export type SpeechFrame = z.infer<typeof SpeechFrameSchema>;

export const TapFrameSchema = z.object({
    "entity_id": z.string(),
});
export type TapFrame = z.infer<typeof TapFrameSchema>;

export const SceneObjectSchema = z.object({
    "asset_ref": z.union([z.null(), z.string()]),
    "class": SceneObjectClassSchema,
    "dimensions": z.array(z.number()),
    "id": z.string(),
    "material_ref": z.string(),
    "movable": z.boolean(),
    "pivot": PivotSchema,
    "pose": PoseSchema,
    "provenance": ProvenanceSchema,
    "refined_class": z.union([z.null(), z.string()]),
    "salience": z.number(),
    "state": EntityStateSchema,
});
export type SceneObject = z.infer<typeof SceneObjectSchema>;

export const SurfaceSchema = z.object({
    "class": SurfaceClassSchema,
    "id": z.string(),
    "material_ref": z.string(),
    "parent": z.union([z.null(), z.string()]).optional(),
    "plane": PlaneSchema,
    "polygon": z.array(z.array(z.number())),
    "provenance": ProvenanceSchema,
    "state": EntityStateSchema,
    "swing": z.union([SwingSchema, z.null()]).optional(),
});
export type Surface = z.infer<typeof SurfaceSchema>;

export const ConstraintReportSchema = z.object({
    "adjustment_distance_m": z.number(),
    "adjustment_reason": z.union([z.null(), z.string()]),
    "alternatives": z.array(AlternativeSchema),
    "applied_pose": z.union([ReportPoseSchema, z.null()]),
    "remaining_notes": z.array(RemainingNoteSchema),
    "requested_pose": z.union([ReportPoseSchema, z.null()]),
    "status": ReportStatusSchema,
    "violations_resolved": z.array(ViolationResolvedSchema),
});
export type ConstraintReport = z.infer<typeof ConstraintReportSchema>;

export const OpParamsSchema = z.object({
    "anchor_id": z.union([z.null(), z.string()]).optional(),
    "catalog_id": z.union([z.null(), z.string()]).optional(),
    "color_hex": z.union([z.null(), z.string()]).optional(),
    "dimensions": z.union([z.array(z.number()), z.null()]).optional(),
    "face_anchor_id": z.union([z.null(), z.string()]).optional(),
    "keep_pose": z.union([z.boolean(), z.null()]).optional(),
    "material_ref": z.union([z.null(), z.string()]).optional(),
    "object": z.union([SceneObjectSchema, z.null()]).optional(),
    "offset_m": z.union([z.number(), z.null()]).optional(),
    "position": z.union([z.array(z.number()), z.null()]).optional(),
    "relation": z.union([PlacementRelationSchema, z.null()]).optional(),
    "scale": z.union([z.number(), z.null()]).optional(),
    "side": z.union([PlacementSideSchema, z.null()]).optional(),
    "style_batch_id": z.union([z.null(), z.string()]).optional(),
    "surface": z.union([SurfaceSchema, z.null()]).optional(),
    "surface_state": z.union([EntityStateSchema, z.null()]).optional(),
    "theme": z.union([z.null(), z.string()]).optional(),
    "undo_op_id": z.union([z.null(), z.string()]).optional(),
    "yaw": z.union([z.number(), z.null()]).optional(),
    "yaw_delta": z.union([z.number(), z.null()]).optional(),
});
export type OpParams = z.infer<typeof OpParamsSchema>;

export const FreeSpaceSummarySchema = z.object({
    "largest_open_rect": OpenRectSchema,
    "wall_clearances": z.array(WallClearanceSchema),
});
export type FreeSpaceSummary = z.infer<typeof FreeSpaceSummarySchema>;

export const RsgSchema = z.object({
    "bounds": BoundsSchema,
    "frame": FrameSchema,
    "lighting": LightingSchema,
    "objects": z.array(SceneObjectSchema),
    "occupancy": OccupancySchema,
    "relations": z.array(RelationSchema),
    "room_id": z.string(),
    "surfaces": z.array(SurfaceSchema),
    "version": z.number(),
});
export type Rsg = z.infer<typeof RsgSchema>;

export const OpCoreSchema = z.object({
    "params": OpParamsSchema,
    "target_ids": z.array(z.string()),
    "type": OpTypeSchema,
});
export type OpCore = z.infer<typeof OpCoreSchema>;

export const ScpSchema = z.object({
    "camera": CameraStateSchema,
    "crosshair_ray": CrosshairRaySchema,
    "free_space_summary": FreeSpaceSummarySchema,
    "last_floor_hit": LastFloorHitSchema,
    "last_tap": LastTapSchema,
    "pointing_ray": PointingRaySchema,
    "ranked_candidates": z.array(RankedCandidateSchema),
    "salience_stack": z.array(z.string()),
    "t": z.number(),
    "visible_entities": z.array(VisibleEntitySchema),
});
export type Scp = z.infer<typeof ScpSchema>;

export const OpSchema = z.object({
    "applied_ts": z.union([z.number(), z.null()]),
    "branch_id": z.string(),
    "caused_by": CausedBySchema,
    "client_ts": z.number(),
    "constraint_report": z.union([ConstraintReportSchema, z.null()]),
    "inverse": z.union([OpCoreSchema, z.null()]),
    "op_id": z.string(),
    "params": OpParamsSchema,
    "seq": z.number(),
    "target_ids": z.array(z.string()),
    "type": OpTypeSchema,
});
export type Op = z.infer<typeof OpSchema>;

export const WsFrameSchema = z.object({
    "applied": z.union([OpSchema, z.null()]).optional(),
    "audio": z.union([AudioFrameSchema, z.null()]).optional(),
    "clarify": z.union([ClarifyFrameSchema, z.null()]).optional(),
    "context": z.union([ScpSchema, z.null()]).optional(),
    "dir": FrameDirectionSchema,
    "error": z.union([ErrorFrameSchema, z.null()]).optional(),
    "hint": z.union([HintFrameSchema, z.null()]).optional(),
    "ops": z.union([z.array(OpSchema), z.null()]).optional(),
    "speech": z.union([SpeechFrameSchema, z.null()]).optional(),
    "t": z.number(),
    "tap": z.union([TapFrameSchema, z.null()]).optional(),
    "type": WsFrameTypeSchema,
});
export type WsFrame = z.infer<typeof WsFrameSchema>;
