#!/usr/bin/env bash
#
# contracts/codegen.sh — the single source of truth flows one way:
#
#     contracts/schema/*.json
#         ├─> ios/SpatialCore/Sources/SpatialCore/Generated/Contracts.swift
#         └─> server/src/contracts.ts
#
# Run this after ANY schema edit. Wire it as a pre-commit hook (tools/install-hooks.sh).
# If Swift and TypeScript types are maintained by hand they diverge by hour 15 and cost
# two hours to a field-name mismatch that reads like a solver bug.
#
#   ./contracts/codegen.sh            regenerate both outputs
#   ./contracts/codegen.sh --check    fail if the outputs are stale (pre-commit / CI)
#
set -euo pipefail

QUICKTYPE_VERSION="23.2.6"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMA_DIR="$REPO_ROOT/contracts/schema"
SWIFT_OUT="$REPO_ROOT/ios/SpatialCore/Sources/SpatialCore/Generated/Contracts.swift"
TS_OUT="$REPO_ROOT/packages/contracts/src/generated.ts"

CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

command -v npx >/dev/null 2>&1 || {
  echo "codegen: npx not found. Install Node 18+ (brew install node), then re-run." >&2
  exit 1
}

# BARE FILENAMES, and we cd into $SCHEMA_DIR before invoking quicktype. This is
# not cosmetic. Cross-file "$ref": "op.schema.json" is resolved relative to the
# referring document; if the sources are passed as ABSOLUTE paths those two URIs
# no longer match, quicktype parses the target a second time as a distinct
# document, and you get PurpleAlternative / FluffyAlternative /
# ConstraintReportClass duplicates instead of one shared type. Relative paths
# make the ref URI and the source URI identical, so every type is emitted once.
#
# Order affects only the readability of the output.
SCHEMAS=(
  rsg.schema.json
  op.schema.json
  scp.schema.json
  constraint_report.schema.json
  ws_frames.schema.json
)

cd "$SCHEMA_DIR"

for f in "${SCHEMAS[@]}"; do
  [[ -f "$f" ]] || { echo "codegen: missing schema $SCHEMA_DIR/$f" >&2; exit 1; }
done

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

banner() {
  # $1 = human label for the output language
  cat <<EOF
// ============================================================================
//  DO NOT EDIT THIS FILE.
//
//  Generated from contracts/schema/*.json by contracts/codegen.sh
//  (quicktype $QUICKTYPE_VERSION). Any hand edit is erased by the next run and
//  will silently desync the $1 side of the contract from the other.
//
//  To change a type: edit the JSON Schema, run ./contracts/codegen.sh,
//  and commit both generated files together.
// ============================================================================

EOF
}

echo "codegen: Swift  -> ${SWIFT_OUT#"$REPO_ROOT"/}"
npx -y "quicktype@$QUICKTYPE_VERSION" \
  --src-lang schema --lang swift \
  --struct-or-class struct \
  --access-level public \
  --mutable-properties \
  --protocol equatable \
  --sendable \
  --density normal \
  --quiet \
  -o "$TMP/Contracts.swift" \
  "${SCHEMAS[@]}"

echo "codegen: TypeScript -> ${TS_OUT#"$REPO_ROOT"/}"
npx -y "quicktype@$QUICKTYPE_VERSION" \
  --src-lang schema --lang typescript-zod \
  --quiet \
  -o "$TMP/contracts.ts" \
  "${SCHEMAS[@]}"

{ banner "Swift";      cat "$TMP/Contracts.swift"; } > "$TMP/Contracts.swift.final"
{ banner "TypeScript"; cat "$TMP/contracts.ts";    } > "$TMP/contracts.ts.final"

if [[ "$CHECK_ONLY" == "1" ]]; then
  status=0
  for pair in "$TMP/Contracts.swift.final:$SWIFT_OUT" "$TMP/contracts.ts.final:$TS_OUT"; do
    gen="${pair%%:*}"; dst="${pair##*:}"
    if ! diff -q "$gen" "$dst" >/dev/null 2>&1; then
      echo "codegen: STALE -> ${dst#"$REPO_ROOT"/}" >&2
      status=1
    fi
  done
  if [[ "$status" != "0" ]]; then
    echo "" >&2
    echo "  Generated types do not match contracts/schema/. Run:" >&2
    echo "      ./contracts/codegen.sh && git add -A" >&2
    exit 1
  fi
  echo "codegen: generated types are up to date."
  exit 0
fi

mkdir -p "$(dirname "$SWIFT_OUT")" "$(dirname "$TS_OUT")"
mv "$TMP/Contracts.swift.final" "$SWIFT_OUT"
mv "$TMP/contracts.ts.final"    "$TS_OUT"

echo "codegen: done."
